module: BluetoothMessageProtocol
author: Kevin A. Hoogheem
github_url: https://github.com/FitnessKit/BluetoothMessageProtocol

readme: README.md

output: docs
clean: true
theme: jony

copyright: '© 2017 Kevin A. Hoogheem'

xcodebuild_arguments: [-scheme,BluetoothMessageProtocol-Package]

custom_categories:
  - name: Base
    children:
    - MemberIdentifier
    - Characteristic
    - CompanyIdentifier
    - Service
    - ServiceData

  - name: GAP
    children:
    - GapAdvertisingType
    - GapDataType
    - GapEventType
    - PeerAddress

  - name: Services - Bluetooth SIG
    children:
    - ServiceGenericAccess
    - ServiceAlertNotification
    - ServiceAutomationInputOutput
    - ServiceBattery
    - ServiceBloodPressure
    - ServiceBodyComposition
    - ServiceBondManagement
    - ServiceContinuousGlucoseMonitoring
    - ServiceCurrentTime
    - ServiceCyclingPower
    - ServiceCyclingSpeedAndCadence
    - ServiceDeviceInformation
    - ServiceEnvironmentalSensing
    - ServiceFitnessMachine
    - ServiceGenericAttribute
    - ServiceGlucose
    - ServiceHealthThermometer
    - ServiceHeartRate
    - ServiceHttpProxy
    - ServiceHumanInterfaceDevice
    - ServiceImmediateAlert
    - ServiceIndoorPositioning
    - ServiceInsulinDelivery
    - ServiceInternetProtocolSupport
    - ServiceLinkLoss
    - ServiceLocationAndNavigation
    - ServiceMeshProvisioning
    - ServiceMeshProxy
    - ServiceNextDSTChange
    - ServiceObjectTransfer
    - ServicePhoneAlertStatus
    - ServicePulseOximeter
    - ServiceReconnectionConfiguration
    - ServiceReferenceTimeUpdate
    - ServiceRunningSpeedAndCadence
    - ServiceScanParameters
    - ServiceTransportDiscovery
    - ServiceTxPower
    - ServiceUserData
    - ServiceWeightScale
   
  - name: Services - Custom
    children:
    - ServiceAppleMidi
    - ServiceCycleOps
    - ServiceDropcam
    - ServiceEliteTrainer
    - ServiceGymConnect
    - ServiceGoogleGlass
    - ServiceKomoot
    - ServiceMyoClassifierEvent
    - ServiceMyoControl
    - ServiceMyoImu
    - ServiceMyoRawEMGData
    - ServiceNordicLegacyDeviceFirmwareUpdate
    - ServiceNordicSecureDeviceFirmwareUpdate
    - ServiceNorthPoleAweDiagnostics
    - ServiceNorthPoleAweHeartRate
    - ServiceTacxAntFec
    - ServiceTexasInstrumentsFirmwareUpdate
    - ServiceTexasInstrumentsSensorTagAccelerometer
    - ServiceTexasInstrumentsSensorTagBarometer
    - ServiceTexasInstrumentsSensorTagControl
    - ServiceTexasInstrumentsSensorTagGyroscope
    - ServiceTexasInstrumentsSensorTagHumidity
    - ServiceTexasInstrumentsSensorTagMagnetometer
    - ServiceTexasInstrumentsSensorTagTemperature
    - ServiceWahooFitnessFirmwareUpdate

  - name: Services - HomeKit Accessory Protocol
    children:
    - ServiceHapPairing
    - ServiceHapProtocolInformationService
    - ServiceHapAccessoryInformation
    - ServiceHapFan 
    - ServiceHapAdvancedFan
    - ServiceHapGarageDoorOpener
    - ServiceHapLightbulb
    - ServiceHapLockManagement
    - ServiceHapLockMechanism
    - ServiceHapOutlet 
    - ServiceHapSwitch
    - ServiceHapThermostat
    - ServiceHapAirQualitySensor
    - ServiceHapSecuritySystem
    - ServiceHapCarbonMonoxideSensor
    - ServiceHapContactSensor
    - ServiceHapDoor
    - ServiceHapHumiditySensor
    - ServiceHapLeakSensor
    - ServiceHapLightSensor
    - ServiceHapMotionSensor
    - ServiceHapOccupancySensor
    - ServiceHapSmokeSensor
    - ServiceHapStatelessProgrammableSwitch
    - ServiceHapTemperatureSensor
    - ServiceHapWindow
    - ServiceHapWindowCovering
    - ServiceHapBatteryService
    - ServiceHapCarbonDioxideSensor
    - ServiceHapCameraRtpStreamManagement
    - ServiceHapMicrophone
    - ServiceHapSpeaker
    - ServiceHapDoorbell
    - ServiceHapSlat
    - ServiceHapFilterMaintenance
    - ServiceHapAirPurifier
    - ServiceHapHeaterCooler
    - ServiceHapHumidifierDehumidifier
    - ServiceHapServiceLabel 
    - ServiceHapIrrigationSystem
    - ServiceHapValve
    - ServiceHapFaucet

  - name: ServiceData - Bluetooth SIG
    children:
    - ServiceDataFitnessMachine
    - ServiceDataMeshProvisioning

  - name: Characteristics - Bluetooth SIG
    children:
    - CharacteristicAerobicHeartRateLowerLimit
    - CharacteristicAerobicHeartRateUpperLimit
    - CharacteristicAerobicThreshold
    - CharacteristicAge
    - CharacteristicAlertCategoryID
    - CharacteristicAlertCategoryIDBitMask
    - CharacteristicAlertLevel
    - CharacteristicAlertNotificationControlPoint
    - CharacteristicAlertStatus
    - CharacteristicAltitude
    - CharacteristicAnaerobicHeartRateLowerLimit
    - CharacteristicAnaerobicHeartRateUpperLimit
    - CharacteristicAnaerobicThreshold
    - CharacteristicAnalog
    - CharacteristicAnalogOutput
    - CharacteristicApparentWindDirection
    - CharacteristicApparentWindSpeed
    - CharacteristicAppearance
    - CharacteristicBarometricPressureTrend
    - CharacteristicBatteryLevel
    - CharacteristicBatteryLevelState
    - CharacteristicBatteryPowerState
    - CharacteristicBloodPressureFeature
    - CharacteristicBloodPressureMeasurement
    - CharacteristicBodyCompositionMeasurement
    - CharacteristicBodySensorLocation
    - CharacteristicBondManagementFeatures
    - CharacteristicContinuousGlucoseMonitoringFeature
    - CharacteristicCrossTrainerData
    - CharacteristicCyclingSpeedCadenceFeature
    - CharacteristicCurrentTime
    - CharacteristicCyclingSpeedCadence
    - CharacteristicDatabaseChangeIncrement
    - CharacteristicDateOfBirth
    - CharacteristicDateofThresholdAssessment
    - CharacteristicDateTime
    - CharacteristicDayDateTime
    - CharacteristicDayOfWeek
    - CharacteristicDeviceName
    - CharacteristicDewPoint
    - CharacteristicDSTOffset
    - CharacteristicElevation
    - CharacteristicEmailAddress
    - CharacteristicFatBurnHeartRateLowerLimit
    - CharacteristicFatBurnHeartRateUpperLimit
    - CharacteristicFirmwareRevisionString
    - CharacteristicFirstName
    - CharacteristicFitnessMachineFeature
    - CharacteristicFitnessMachineStatus
    - CharacteristicFiveZoneHeartRateLimits
    - CharacteristicFloorNumber
    - CharacteristicGender
    - CharacteristicGustFactor
    - CharacteristicHardwareRevisionString
    - CharacteristicHeartRateControlPoint
    - CharacteristicHeartRateMax
    - CharacteristicHeartRateMeasurement
    - CharacteristicHeatIndex
    - CharacteristicHeight
    - CharacteristicHipCircumference
    - CharacteristicHTTPControlPoint
    - CharacteristicHTTPEntityBody
    - CharacteristicHTTPHeaders
    - CharacteristicHTTPSSecurity
    - CharacteristicHTTPStatusCode
    - CharacteristicHumidity
    - CharacteristicIndoorBikeData
    - CharacteristicIntermediateCuffPressure
    - CharacteristicIntermediateTemperature
    - CharacteristicLanguage
    - CharacteristicLastName
    - CharacteristicLatitude
    - CharacteristicLocalEastCoordinate
    - CharacteristicLocalNorthCoordinate
    - CharacteristicLocalTimeInformation
    - CharacteristicLocationName
    - CharacteristicLocationNavigationFeature
    - CharacteristicLongitude
    - CharacteristicMagneticDeclination
    - CharacteristicManufacturerNameString
    - CharacteristicMaximumRecommendedHeartRate
    - CharacteristicMeasurementInterval
    - CharacteristicModelNumberString
    - CharacteristicNetworkAvailability
    - CharacteristicNewAlert
    - CharacteristicObjectName
    - CharacteristicObjectSize
    - CharacteristicPnPID
    - CharacteristicPollenConcentration
    - CharacteristicPosition2D
    - CharacteristicPosition3D
    - CharacteristicPressure
    - CharacteristicRainfall
    - CharacteristicRestingHeartRate
    - CharacteristicRingerSetting
    - CharacteristicRowerData
    - CharacteristicScanIntervalWindow
    - CharacteristicScanRefresh
    - CharacteristicSensorLocation
    - CharacteristicSerialNumberString
    - CharacteristicSoftwareRevisionString
    - CharacteristicSportTypeForAerobicAndAnaerobicThresholds
    - CharacteristicStairClimberData
    - CharacteristicStepClimberData
    - CharacteristicString
    - CharacteristicSupportedHeartRateRange
    - CharacteristicSupportedInclinationRange
    - CharacteristicSupportedPowerRange
    - CharacteristicSupportedResistanceLevel
    - CharacteristicSupportedSpeedRange
    - CharacteristicTemperature
    - CharacteristicTemperatureCelsius
    - CharacteristicTemperatureFahrenheit
    - CharacteristicTemperatureMeasurement
    - CharacteristicTemperatureType
    - CharacteristicThreeZoneHeartRateLimits
    - CharacteristicTimeSource
    - CharacteristicTimeUpdateControlPoint
    - CharacteristicTimeUpdateState
    - CharacteristicTimeWithDst
    - CharacteristicTimeZone
    - CharacteristicTrainingStatus
    - CharacteristicTreadmillData
    - CharacteristicTrueWindDirection
    - CharacteristicTrueWindSpeed
    - CharacteristicTwoZoneHeartRateLimit
    - CharacteristicTxPowerLevel
    - CharacteristicUniformResourceIdentifier
    - CharacteristicUnreadAlertStatus
    - CharacteristicUserIndex
    - CharacteristicUVIndex
    - CharacteristicV02Max
    - CharacteristicWaistCircumference
    - CharacteristicWeight
    - CharacteristicWeightMeasurement
    - CharacteristicWeightScaleFeature
    - CharacteristicWindChill

  - name: Characteristic - Mesh
    children:
    - CharacteristicMeshProvisioningDataIn
    - CharacteristicMeshProvisioningDataOut 
    - CharacteristicMeshProxyDataIn
    - CharacteristicMeshProxyDataOut

  - name: Characteristic - Custom
    children:
    - CharacteristicGymConnectEquipmentType
    - CharacteristicGymConnectEquipmentState
    - CharacteristicGymConnectEquipmentStateName
    - CharacteristicGymConnectMeasurement
    - CharacteristicGymConnectWorkoutProgramName
    - CharacteristicNorthPoleAweDiagnostics
    - CharacteristicNorthPoleAweHeartRateMeasurement
    - CharacteristicNorthPoleAweWorkoutInformation
    - CharacteristicTacxAntFecReceive
    - CharacteristicTacxAntFecSend

  - name: Manufacturer Data
    children:
    - ManufacturerData
    - ManufacturerDataAltBeacon
    - ManufacturerDataAppleHomeKit
    - ManufacturerDataAppleHomeKitEncryptedNotification
    - ManufacturerDataAppleiBeacon
    - ManufacturerDataGymConnect
    - ManufacturerDataPolarHeartRate

  - name: Fitness Machine Control
    children:
    - FitnessMachineControlCode
    - FitnessMachineControlProcedure
    - FitnessMachineProcedureRequestControl
    - FitnessMachineProcedureReset
    - FitnessMachineProcedureSetTargetSpeed
    - FitnessMachineProcedureSetTargetInclination
    - FitnessMachineProcedureSetTargetResistanceLevel
    - FitnessMachineProcedureSetTargetPower
    - FitnessMachineProcedureSetTargetHeartRate
    - FitnessMachineProcedureStartResume
    - FitnessMachineProcedureStopPause
    - FitnessMachineProcedureSetTargetedExpendedEnergy
    - FitnessMachineProcedureSetTargetedNumberOfSteps
    - FitnessMachineProcedureSetTargetedNumberOfStrides 
    - FitnessMachineProcedureSetTargetedDistance
    - FitnessMachineProcedureSetTargetedTrainingTime
    - FitnessMachineProcedureSetTargetedTimeInTwoHrZone
    - FitnessMachineProcedureSetTargetedTimeInThreeHrZone
    - FitnessMachineProcedureSetTargetedTimeInFiveHrZone
    - FitnessMachineProcedureSeWheelCircumference
    - FitnessMachineProcedureSetSpinDownControl
    - FitnessMachineProcedureSetTargetedCadence
    - FitnessMachineProcedureResponse

  - name: Fitness Machine Control Response Type
    children:
    - FitnessMachineControlResponseType
    - FitnessMachineControlResponseTypeSpinDown

  - name: Fitness Machine Status
    children:
    - FitnessMachineStatusCode
    - FitnessMachineStatus
    - FitnessMachineStatusGeneric
    - FitnessMachineStatusStopPause
    - FitnessMachineStatusTargetSpeed
    - FitnessMachineStatusTargetIncline
    - FitnessMachineStatusTargetResistanceLevel
    - FitnessMachineStatusTargetPower
    - FitnessMachineStatusTargetHeartRate
    - FitnessMachineStatusTargetedExpendedEnergyChanged
    - FitnessMachineStatusTargetedSteps
    - FitnessMachineStatusTargetedStrides
    - FitnessMachineStatusTargetedDistance  
    - FitnessMachineStatusTargetedTrainingTime
    - FitnessMachineStatusTargetedTimeInTwoHrZoneChanged
    - FitnessMachineStatusTargetedTimeInThreeHrZoneChanged
    - FitnessMachineStatusTargetedTimeInFiveHrZoneChanged
    - FitnessMachineStatusWheelCircumference
    - FitnessMachineStatusSpinDown
    - FitnessMachineStatusTargetedCadence

  - name: Fitness Machine Types
    children:
    - FitnessMachineEnergy
    - FitnessMachineInclinationType
    - FitnessMachineMovementDirection
    - FitnessMachinePowerType
    - FitnessMachineTargetCadence
    - FitnessMachineTargetDistance
    - FitnessMachineTargetExpendedEnergy
    - FitnessMachineTargetResistanceLevelType
    - FitnessMachineTargetTime
    - FitnessMachineTargetTimeInTwoHrZone
    - FitnessMachineTargetTimeInThreeHrZone
    - FitnessMachineTargetTimeInFiveHrZone
    - FitnessMachineTime
    - FitnessMachineStopPauseType
    - FitnessMachineSpeedType
    - FitnessMachineWheelCircumferenceType

  - name: HomeKit
    children:
    - HomeKitAccessoryCategory
    - HomeKitPairingErrorType
    - HomeKitPairingMethodType
    - HomeKitSoftwareAuthenticationTlvType
    - HomeKitPairingTlvType

  - name: Mesh
    children:
    - ProvisioningSize
    - ProvisioningAttentionTimer
    - MeshModelIdentifier
    - ModelIdentifierType
    - MeshOutOfBandInformation
    - MeshTransitionTime

  - name: Mesh Beacon
    children:
    - MeshBeacon
    - MeshBeaconType
    - MeshBeaconSecureNetwork
    - MeshBeaconUnprovisioned

  - name: Mesh Message
    children:
     - MeshMessage
     - GenericOnOffState
     - MeshMessageGenericOnOffGet
     - MeshMessageGenericOnOffSet
     - MeshMessageGenericOnOffSetUnacknowledged
     - MeshMessageGenericOnOffStatus
     - MeshMessageGenericLevelGet
     - MeshMessageGenericLevelSet
     - MeshMessageGenericLevelSetUnacknowledged
     - MeshMessageGenericLevelSatus
     - MeshMessageGenericDeltaSet
     - MeshMessageGenericDeltaSetUnacknowledged
     - MeshMessageGenericMoveSet
     - MeshMessageGenericMoveSetUnacknowledged

  - name: Mesh Provisioning
    children:
    - ProvisioningData
    - ProvisioningDataUnit
    - ProvisioningDataUnitType
    - ProvisioningDataUnitCapabilities
    - ProvisioningDataUnitInvite
    - ProvisioningDataUnitStart
    - ProvisioningDataUnitPublicKey
    - ProvisioningDataUnitInputComplete
    - ProvisioningDataUnitConfirmation
    - ProvisioningDataUnitRandom
    - ProvisioningDataUnitData
    - ProvisioningDataUnitComplete
    - ProvisioningDataUnitFailed

  - name: Provisioning Authentication
    children:
    - ProvisioningAuthenticationMethod
    - ProvisioningAuthentication
    - ProvisioningAuthenticationMethodNone
    - ProvisioningAuthenticationMethodStatic
    - ProvisioningAuthenticationMethodOutput
    - ProvisioningAuthenticationMethodInput 

  - name: Mesh Proxy
    children:
    - ProxyDataUnit
    - ProxyMessageType
    - ProxyDataUnitBeacon
    - ProxyDataUnitProvisioning

