//
//  MemberIdentifierSupportedExtension.swift
//  BluetoothMessageProtocol
//
//  Created by Kevin Hoogheem on 3/31/18.
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
import Foundation

// MARK: - Supported
public extension MemberIdentifier {

    /// Array of all Supported MemberIdentifier values
    static var supportedMemberIdentifers: [MemberIdentifier] = {

        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD0F, name: "AEON MOTOR CO.,LTD."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD10, name: "AEON MOTOR CO.,LTD."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD11, name: "AEON MOTOR CO.,LTD."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD12, name: "AEON MOTOR CO.,LTD."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD13, name: "BRG Sports, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD14, name: "BRG Sports, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD16, name: "Sensitech, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD17, name: "LEGIC Identsystems AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD18, name: "LEGIC Identsystems AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD19, name: "Smith & Nephew Medical Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD1A, name: "CSIRO"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD1B, name: "Helios Sports, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD1C, name: "Brady Worldwide Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD1D, name: "Samsung Electronics Co., Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD1E, name: "Plume Design Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD1F, name: "3M"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD20, name: "GN Hearing A/S"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD21, name: "Huawei Technologies Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD22, name: "Huawei Technologies Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD23, name: "DOM Sicherheitstechnik GmbH & Co. KG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD24, name: "GD Midea Air-Conditioning Equipment Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD25, name: "GD Midea Air-Conditioning Equipment Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD26, name: "Novo Nordisk A/S"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD27, name: "i2Systems"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD28, name: "Julius Blum GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD29, name: "Asahi Kasei Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD2A, name: "Sony Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD2B, name: "The Access Technologies"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD2C, name: "The Access Technologies"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD2D, name: "Xiaomi Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD2E, name: "Bitstrata Systems Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD2F, name: "Bitstrata Systems Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD30, name: "Sesam Solutions BV"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD31, name: "LG Electronics Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD32, name: "Gemalto Holding BV"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD33, name: "DashLogic, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD34, name: "Aerosens LLC."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD35, name: "Transsion Holdings Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD36, name: "Google LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD37, name: "TireCheck GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD38, name: "Danfoss A/S"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD39, name: "PREDIKTAS"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD3A, name: "Verkada Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD3B, name: "Verkada Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD3C, name: "Redline Communications Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD3D, name: "Woan Technology (Shenzhen) Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD3E, name: "Pure Watercraft, inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD3F, name: "Cognosos, Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD40, name: "Beflex Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD41, name: "Amazon Lab126"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD42, name: "Globe (Jiangsu) Co.,Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD43, name: "Apple Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD44, name: "Apple Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD45, name: "GB Solution co.,Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD46, name: "Lemco IKE"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD47, name: "Liberty Global Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD48, name: "Geberit International AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD49, name: "Panasonic Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD4A, name: "Sigma Elektro GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD4B, name: "Samsung Electronics Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD4C, name: "Adolf Wuerth GmbH & Co KG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD4D, name: "70mai Co.,Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD4E, name: "70mai Co.,Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD4F, name: "Forkbeard Technologies AS"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD50, name: "Hangzhou Tuya Information Technology Co., Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD51, name: "UTC Fire and Security"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD52, name: "UTC Fire and Security"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD53, name: "PCI Private Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD54, name: "Qingdao Haier Technology Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD55, name: "Braveheart Wireless, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD56, name: "Resmed Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD57, name: "Volvo Car Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD58, name: "Volvo Car Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD59, name: "Samsung Electronics Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD5A, name: "Samsung Electronics Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD5B, name: "V2SOFT INC."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD5C, name: "React Mobile"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD5D, name: "maxon motor ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD5E, name: "Tapkey GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD5F, name: "Oculus VR, LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD60, name: "Sercomm Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD61, name: "Arendi AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD62, name: "Fitbit, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD63, name: "Fitbit, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD64, name: "INRIA"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD65, name: "Razer Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD66, name: "Zebra Technologies Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD67, name: "Montblanc Simplo GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD68, name: "Ubique Innovation AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD69, name: "Samsung Electronics Co., Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD6A, name: "Emerson"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD6B, name: "rapitag GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD6C, name: "Samsung Electronics Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD6D, name: "Sigma Elektro GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD6E, name: "Polidea sp. z o.o."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD6F, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD70, name: "GuangDong Oppo Mobile Telecommunications Corp., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD71, name: "GN Hearing A/S"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD72, name: "Logitech International SA"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD73, name: "BRControls Products BV"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD74, name: "BRControls Products BV"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD75, name: "Insulet Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD76, name: "Insulet Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD77, name: "Withings"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD78, name: "Withings"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD79, name: "Withings"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD7A, name: "Withings"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD7B, name: "WYZE LABS, INC."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD7C, name: "Toshiba Information Systems(Japan) Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD7D, name: "Center for Advanced Research Wernher Von Braun"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD7E, name: "Samsung Electronics Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD7F, name: "Husqvarna AB"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD80, name: "Phindex Technologies, Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD81, name: "CANDY HOUSE, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD82, name: "Sony Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD83, name: "iNFORM Technology GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD84, name: "Tile, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD85, name: "Husqvarna AB"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD86, name: "Abbott"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD87, name: "Google LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD88, name: "Urbanminded LTD"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD89, name: "Urbanminded LTD"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD8A, name: "Signify Netherlands B.V."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD8B, name: "Jigowatts Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD8C, name: "Google LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD8D, name: "quip NYC Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD8E, name: "Motorola Solutions"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD8F, name: "Matrix ComSec Pvt. Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD90, name: "Guangzhou SuperSound Information Technology Co.,Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD91, name: "Groove X, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD92, name: "Qualcomm Technologies International, Ltd. (QTIL)"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD93, name: "Bayerische Motoren Werke AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD94, name: "Hewlett Packard Enterprise"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD95, name: "Rigado"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD96, name: "Google LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD97, name: "June Life, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD98, name: "Disney Worldwide Services, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD99, name: "ABB Oy"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD9A, name: "Huawei Technologies Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD9B, name: "Huawei Technologies Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD9C, name: "Huawei Technologies Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD9D, name: "Gastec Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD9E, name: "The Coca-Cola Company"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFD9F, name: "VitalTech Affiliates LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDA0, name: "Secugen Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDA1, name: "Groove X, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDA2, name: "Groove X, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDA3, name: "Inseego Corp."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDA4, name: "Inseego Corp."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDA5, name: "Neurostim OAB, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDA6, name: "WWZN Information Technology Company Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDA7, name: "WWZN Information Technology Company Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDA8, name: "PSA Peugeot Citroën"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDA9, name: "Rhombus Systems, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDAA, name: "Xiaomi Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDAB, name: "Xiaomi Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDAC, name: "Tentacle Sync GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDAD, name: "Houwa System Design, k.k."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDAE, name: "Houwa System Design, k.k."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDAF, name: "Wiliot LTD"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDB0, name: "Proxy Technologies, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDB1, name: "Proxy Technologies, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDB2, name: "Portable Multimedia Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDB3, name: "Audiodo AB"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDB4, name: "HP Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDB5, name: "ECSG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDB6, name: "GWA Hygiene GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDB7, name: "LivaNova USA Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDB8, name: "LivaNova USA Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDB9, name: "Comcast Cable Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDBA, name: "Comcast Cable Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDBB, name: "Profoto"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDBC, name: "Emerson"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDBD, name: "Clover Network, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDBE, name: "California Things Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDBF, name: "California Things Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDC0, name: "Hunter Douglas"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDC1, name: "Hunter Douglas"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDC2, name: "Baidu Online Network Technology (Beijing) Co., Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDC3, name: "Baidu Online Network Technology (Beijing) Co., Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDC4, name: "Simavita (Aust) Pty Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDC5, name: "Automatic Labs"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDC6, name: "Eli Lilly and Company"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDC7, name: "Eli Lilly and Company"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDC8, name: "Hach Danaher"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDC9, name: "Busch-Jaeger Elektro GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDCA, name: "Fortin Electronic Systems"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDCB, name: "Meggitt SA"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDCC, name: "Shoof Technologies"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDCD, name: "Qingping Technology (Beijing) Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDCE, name: "SENNHEISER electronic GmbH & Co. KG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDCF, name: "Nalu Medical, Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDD0, name: "Huawei Technologies Co., Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDD1, name: "Huawei Technologies Co., Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDD2, name: "Bose Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDD3, name: "FUBA Automotive Electronics GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDD4, name: "LX Solutions Pty Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDD5, name: "Brompton Bicycle Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDD6, name: "Ministry of Supply"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDD7, name: "Emerson"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDD8, name: "Jiangsu Teranovo Tech Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDD9, name: "Jiangsu Teranovo Tech Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDDA, name: "MHCS"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDDB, name: "Samsung Electronics Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDDC, name: "4iiii Innovations Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDDD, name: "Arch Systems Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDDE, name: "Noodle Technology Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDDF, name: "Harman International"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDE0, name: "John Deere"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDE1, name: "Fortin Electronic Systems"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDE2, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDE3, name: "Abbott Diabetes Care"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDE4, name: "JUUL Labs, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDE5, name: "SMK Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDE6, name: "Intelletto Technologies Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDE7, name: "SECOM Co., LTD"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDE8, name: "Robert Bosch GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDE9, name: "Spacesaver Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDEA, name: "SeeScan, Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDEB, name: "Syntronix Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDEC, name: "Mannkind Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDED, name: "Pole Star"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDEE, name: "Huawei Technologies Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDEF, name: "ART AND PROGRAM, INC."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDF0, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDF1, name: "LAMPLIGHT Co.,Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDF2, name: "AMICCOM Electronics Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDF3, name: "Amersports"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDF4, name: "O. E. M. Controls, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDF5, name: "Milwaukee Electric Tools"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDF6, name: "AIAIAI ApS"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDF7, name: "HP Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDF8, name: "Onvocal"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDF9, name: "INIA"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDFA, name: "Tandem Diabetes Care"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDFB, name: "Tandem Diabetes Care"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDFC, name: "Optrel AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDFD, name: "RecursiveSoft Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDFE, name: "ADHERIUM(NZ) LIMITED"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFDFF, name: "OSRAM GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE00, name: "Amazon.com Services, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE01, name: "Duracell U.S. Operations Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE02, name: "Robert Bosch GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE03, name: "Amazon.com Services, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE04, name: "OpenPath Security Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE05, name: "CORE Transport Technologies NZ Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE06, name: "Qualcomm Technologies, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE08, name: "Microsoft"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE09, name: "Pillsy, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE0A, name: "ruwido austria gmbh"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE0B, name: "ruwido austria gmbh"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE0C, name: "Procter & Gamble"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE0D, name: "Procter & Gamble"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE0E, name: "Setec Pty Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE0F, name: "Philips Lighting B.V."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE10, name: "Lapis Semiconductor Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE11, name: "GMC-I Messtechnik GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE12, name: "M-Way Solutions GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE13, name: "Apple Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE14, name: "Flextronics International USA Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE15, name: "Amazon.com Services, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE16, name: "Footmarks, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE17, name: "Telit Wireless Solutions GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE18, name: "Runtime, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE19, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE1A, name: "Tyto Life LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE1B, name: "Tyto Life LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE1C, name: "NetMedia, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE1D, name: "Illuminati Instrument Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE1E, name: "Smart Innovations Co., Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE1F, name: "Garmin International, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE20, name: "Emerson"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE21, name: "Bose Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE22, name: "Zoll Medical Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE23, name: "Zoll Medical Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE24, name: "August Home Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE25, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE26, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE27, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE28, name: "Ayla Networks"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE29, name: "Gibson Innovations"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE2A, name: "DaisyWorks, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE2B, name: "ITT Industries"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE2C, name: "Google Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE2D, name: "SMART INNOVATION Co.,Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE2E, name: "ERi,Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE2F, name: "CRESCO Wireless, Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE30, name: "Volkswagen AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE31, name: "Volkswagen AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE32, name: "Pro-Mark, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE33, name: "CHIPOLO d.o.o."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE34, name: "SmallLoop LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE35, name: "HUAWEI Technologies Co., Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE36, name: "HUAWEI Technologies Co., Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE37, name: "Spaceek LTD"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE38, name: "Spaceek LTD"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE39, name: "TTS Tooltechnic Systems AG & Co. KG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE3A, name: "TTS Tooltechnic Systems AG & Co. KG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE3B, name: "Dolby Laboratories"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE3C, name: "Alibaba"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE3D, name: "BD Medical"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE3E, name: "BD Medical"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE3F, name: "Friday Labs Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE40, name: "Inugo Systems Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE41, name: "Inugo Systems Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE42, name: "Nets A/S"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE43, name: "Andreas Stihl AG & Co. KG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE44, name: "SK Telecom"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE45, name: "Snapchat Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE46, name: "B&O Play A/S"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE47, name: "General Motors"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE48, name: "General Motors"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE49, name: "SenionLab AB"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE4A, name: "OMRON HEALTHCARE Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE4B, name: "Philips Lighting B.V."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE4C, name: "Volkswagen AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE4D, name: "Casambi Technologies Oy"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE4E, name: "NTT docomo"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE4F, name: "Molekule, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE50, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE51, name: "SRAM"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE52, name: "SetPoint Medical"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE53, name: "3M"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE54, name: "Motiv, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE55, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE56, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE57, name: "Dotted Labs"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE58, name: "Nordic Semiconductor ASA"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE59, name: "Nordic Semiconductor ASA"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE5A, name: "Chronologics Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE5B, name: "GT-tronics HK Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE5C, name: "million hunters GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE5D, name: "Grundfos A/S"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE5E, name: "Plastc Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE5F, name: "Eyefi, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE60, name: "Lierda Science & Technology Group Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE61, name: "Logitech International SA"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE62, name: "Indagem Tech LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE63, name: "Connected Yard, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE64, name: "Siemens AG"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE65, name: "CHIPOLO d.o.o."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE66, name: "Intel Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE67, name: "Lab Sensor Solutions"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE68, name: "Qualcomm Life Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE69, name: "Qualcomm Life Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE6A, name: "Kontakt Micro-Location Sp. z o.o."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE6B, name: "TASER International, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE6C, name: "TASER International, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE6D, name: "The University of Tokyo"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE6E, name: "The University of Tokyo"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE6F, name: "LINE Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE70, name: "Beijing Jingdong Century Trading Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE71, name: "Plume Design Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE72, name: "St. Jude Medical, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE73, name: "St. Jude Medical, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE74, name: "unwire"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE75, name: "TangoMe"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE76, name: "TangoMe"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE77, name: "Hewlett-Packard Company"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE78, name: "Hewlett-Packard Company"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE79, name: "Zebra Technologies"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE7A, name: "Bragi GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE7B, name: "Orion Labs, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE7C, name: "Telit Wireless Solutions"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE7D, name: "Aterica Health Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE7E, name: "Awear Solutions Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE7F, name: "Doppler Lab"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE80, name: "Doppler Lab"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE81, name: "Medtronic Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE82, name: "Medtronic Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE83, name: "Blue Bite"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE84, name: "RF Digital Corp"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE85, name: "RF Digital Corp"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE86, name: "HUAWEI Technologies Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE87, name: "Qingdao Yeelink Information Technology Co., Ltd."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE88, name: "SALTO SYSTEMS S.L."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE89, name: "B&O Play A/S"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE8A, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE8B, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE8C, name: "TRON Forum"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE8D, name: "Interaxon Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE8E, name: "ARM Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE8F, name: "CSR"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE90, name: "JUMA"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE91, name: "Shanghai Imilab Technology Co.,Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE92, name: "Jarden Safety & Security"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE93, name: "OttoQ Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE94, name: "OttoQ Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE95, name: "Xiaomi Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE96, name: "Tesla Motor Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE97, name: "Tesla Motor Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE98, name: "Currant, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE99, name: "Currant, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE9A, name: "Estimote"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE9B, name: "Samsara Networks, Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE9C, name: "GSI Laboratories, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE9D, name: "Mobiquity Networks Inc"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE9E, name: "Dialog Semiconductor B.V."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFE9F, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEA0, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEA1, name: "Intrepid Control Systems, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEA2, name: "Intrepid Control Systems, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEA3, name: "ITT Industries"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEA4, name: "Paxton Access Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEA5, name: "GoPro, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEA6, name: "GoPro, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEA7, name: "UTC Fire and Security"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEA8, name: "Savant Systems LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEA9, name: "Savant Systems LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEAA, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEAB, name: "Nokia Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEAC, name: "Nokia Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEAD, name: "Nokia Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEAE, name: "Nokia Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEAF, name: "Nest Labs Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEB0, name: "Nest Labs Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEB1, name: "Electronics Tomorrow Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEB2, name: "Microsoft Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEB3, name: "Taobao"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEB4, name: "WiSilica Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEB5, name: "WiSilica Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEB6, name: "Vencer Co, Ltd"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEB7, name: "Facebook, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEB8, name: "Facebook, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEB9, name: "LG Electronics"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEBA, name: "Tencent Holdings Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEBB, name: "adafruit industries"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEBC, name: "Dexcom, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEBD, name: "Clover Network, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEBE, name: "Bose Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEBF, name: "Nod, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEC0, name: "KDDI Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEC1, name: "KDDI Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEC2, name: "Blue Spark Technologies, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEC3, name: "360fly, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEC4, name: "PLUS Location Systems"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEC5, name: "Realtek Semiconductor Corp."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEC6, name: "Kocomojo, LLC"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEC7, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEC8, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEC9, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFECA, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFECB, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFECC, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFECD, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFECE, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFECF, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFED0, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFED1, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFED2, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFED3, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFED4, name: "Apple, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFED5, name: "Plantronics Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFED6, name: "Broadcom Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFED7, name: "Broadcom Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFED8, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFED9, name: "Pebble Technology Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEDA, name: "ISSC Technologies Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEDB, name: "Perka, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEDC, name: "Jawbone"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEDD, name: "Jawbone"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEDE, name: "Coin, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEDF, name: "Design SHIFT"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEE0, name: "Anhui Huami Information Technology Co."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEE1, name: "Anhui Huami Information Technology Co."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEE2, name: "Anki, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEE3, name: "Anki, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEE4, name: "Nordic Semiconductor ASA"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEE5, name: "Nordic Semiconductor ASA"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEE6, name: "Silvair, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEE7, name: "Tencent Holdings Limited"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEE8, name: "Quintic Corp."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEE9, name: "Quintic Corp."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEEA, name: "Swirl Networks, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEEB, name: "Swirl Networks, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEEC, name: "Tile, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEED, name: "Tile, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEEE, name: "Polar Electro Oy"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEEF, name: "Polar Electro Oy"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEF0, name: "Intel"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEF1, name: "CSR"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEF2, name: "CSR"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEF3, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEF4, name: "Google Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEF5, name: "Dialog Semiconductor GmbH"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEF6, name: "Wicentric, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEF7, name: "Aplix Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEF8, name: "Aplix Corporation"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEF9, name: "PayPal, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEFA, name: "PayPal, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEFB, name: "Telit Wireless Solutions"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEFC, name: "Gimbal, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEFD, name: "Gimbal, Inc."))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEFE, name: "GN ReSound A/S"))
        allMemberIdentifiers.append(MemberIdentifier(assignedNumber: 0xFEFF, name: "GN Netcom"))

        return allMemberIdentifiers
    }()
}
